### ISSUE TITLE
Output Parameters

### ISSUE THREAD

**Issue by infinitless** [amchess/ShashChess#23]
What would really help is a "Verbose" option that displays the value ratios of Mobility, Material, Space, Compactness, KP density, King Safety and the preferred algorithm T, C, P, TC,CP or TCP at every move. That is the real value added as we would know how this engine "thinks". Without it, its just another engine in a black box.

**Comment by amchess** [comment]
Shashin values are
Mobility, Material, Safety and the two space factors (expansion factor and packaging density).
By those values the engine uses the drift chart to determine a value for the position and so the algorithm to follow (Tal, Capablanca and Petrosian).
Shashchess is a Stockfish derivate. So, it cannnot explicitely calculate the above five values because it would be a waste of time and a great decrease in strength. Conversely, it uses Stockfish code to determine the position's nature/algorithm and direct the search and the eval.
We also have an offline application using Shashchess to calculate those values, but for now it's private.

**Comment by infinitless** [comment]
Yes, but then it's not really an attempt to implement the book then is it? :) 

Not sure if it's a waste of time - I can calculate the five parameters within about 90 seconds for any position - so for a CPU/GPU it should be a piece of cake.

The engine then, is just modified Stockfish.

Sorry, don't mean to dilute the effort put it, the description is not accurate though.

Peace.
